// The four contract interfaces, generated by `hardhat compile` in contracts/.
export { quillRegistryRegistrarAbi as registryAbi } from "./abi/quillRegistryRegistrarAbi";
export { quillControllerAbi as controllerAbi } from "./abi/quillControllerAbi";
export { quillResolverAbi as resolverAbi } from "./abi/quillResolverAbi";
export { quillReverseRegistrarAbi as reverseAbi } from "./abi/quillReverseRegistrarAbi";

export const PROFILE_KEYS = ["avatar", "description", "url", "com.twitter"] as const;
export type ProfileKey = (typeof PROFILE_KEYS)[number];
