"use client";

import { BRAND } from "@/lib/brand";
import type { ViewModel } from "@/lib/viewModel";
import { Arrow, PageHeading } from "../ui/Basics";

export function Developers({ v }: { v: ViewModel }) {
  return (
    <>
      <PageHeading number="07" title={`Build with ${BRAND.name}.`}>
        Human-readable input. Explicit, chain-aware resolution.
      </PageHeading>
      <div className="developer-layout">
        <div>
          <p className="eyebrow">{"/// INTEGRATION NOTES"}</p>
          <h2>Resolve with intention.</h2>
          <p>Independent namespace, no automatic ENS, Robinhood Wallet or browser support. Use chain ID + registry + node as identity.</p>
          <ol className="integration-list">
            <li>Validate the deployment and chain.</li>
            <li>Resolve the canonical name from RPC.</li>
            <li>Reject an unresolved destination.</li>
            <li>Recheck immediately before payment.</li>
          </ol>
          <a className="text-link" href="#profile">
            Inspect a public profile <Arrow />
          </a>
        </div>
        <div className="code-panel">
          <span className="mono">TYPESCRIPT / {BRAND.sdkPackage.toUpperCase()}</span>
          <pre>
            <code>{`import { ${BRAND.sdkFactory} } from '${BRAND.sdkPackage}';

const ${BRAND.sdkVariable} = ${BRAND.sdkFactory}(publicClient, deployment);
const recipient = await ${BRAND.sdkVariable}.resolveName('${BRAND.exampleName}');
if (!recipient) throw new Error('Unresolved');`}</code>
          </pre>
        </div>
      </div>
      <section className="config-section">
        <p className="eyebrow">{"/// DEPLOYMENT CONFIGURATION"}</p>
        <h2>{v.configured ? "Configured manifest" : "No deployment configured."}</h2>
        <p>Public configuration only. Contract wiring is validated by the SDK before use.</p>
        <pre className="manifest">
          <code>{v.manifest}</code>
        </pre>
        <details>
          <summary>Contract interfaces &amp; resolution rules</summary>
          <p>The SDK reads RPC directly. Never substitute the NFT owner for an unresolved destination.</p>
          <p>
            ABI source: <code>src/lib/abi/</code>, generated by <code>hardhat compile</code> in <code>contracts/</code>. Full ABI and deployment verification
            remain separate from this interface.
          </p>
          <p>
            Root node: <code>keccak256(bytes32(0) ‖ keccak256(&quot;{BRAND.tld}&quot;))</code>. Node: <code>keccak256(root ‖ keccak256(label))</code>. Token id:{" "}
            <code>uint256(node)</code>.
          </p>
        </details>
      </section>
    </>
  );
}
