import * as fs from "fs";
import * as path from "path";
import type { HardhatRuntimeEnvironment } from "hardhat/types";

export const frontendAbiDir = path.resolve(__dirname, "../../../src/lib/abi");

const EXPORTED = ["QuillRegistryRegistrar", "QuillController", "QuillResolver", "QuillReverseRegistrar"] as const;

/**
 * Writes each contract's ABI to ../src/lib/abi/<name>Abi.ts as a TypeScript
 * `as const` literal, so the site imports the exact interface it was
 * compiled against and viem infers argument and return types.
 */
export async function exportAbis(hre: HardhatRuntimeEnvironment): Promise<void> {
  fs.mkdirSync(frontendAbiDir, { recursive: true });
  for (const name of EXPORTED) {
    const artifact = await hre.artifacts.readArtifact(name);
    const ident = name[0].toLowerCase() + name.slice(1) + "Abi";
    fs.writeFileSync(
      path.join(frontendAbiDir, `${ident}.ts`),
      `// Generated by contracts/scripts/lib/exportAbi.ts on every hardhat compile — do not edit.\nexport const ${ident} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
    );
  }
}
